### ISSUE TITLE
The title of the TLS BR should include a reference to TLS/serverAuth 

### ISSUE THREAD

**Issue by srdavidson** [cabforum/servercert#420] opened 2023-02-09 15:34 UTC
It has been pointed out that the CABF now has several "baseline requirements" and that the "Baseline Requirements for the Issuance and Management of Publicly-Trusted Certificates" does not adequately describe the type of certificates.  This can create confusion.  By contrast, the code signing and S/MIME documents name the certificate type in their titles.

The Server Cert WG should consider updating the name of the TLS BR to specifically identify TLS serverAuth certificates.

**Comment by barrini** [comment] 2023-02-09 16:02
Agreed.

**Comment by ryancdickson** [comment] 2023-02-09 16:32
+1

**Comment by BenWilson-Mozilla** [comment] 2023-02-09 17:03
This is a duplicate of Issue #337

**Comment by barrini** [comment] 2024-06-20 15:19
Already done.

**Closed by barrini** 2024-06-20 15:19 UTC
Labels: baseline-requirements
